### ISSUE TITLE
Add explanatory header to clock face

### ISSUE THREAD

**Issue by daniel-moon32** [BeautifulTrouble/h4i-uiuc-climate-clock-widget#32]
## Learning objectives

- Objective

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Todo

## Useful links

- Useful link

## Starter Product Questions

These are some general questions that you can ask Nikhil or Archna. Feel free to ask additional, more in-depth questions, like specifications that you think we overlooked.

- What role does this play within the project?
- Why is it better than <x> alternative (i.e. leaving the clock without a header)?
- Where would users use this feature? In what situation?
- How does the header utilize dynamic property?

**Comment by Archna-1** [comment]
Fixed in an earlier PR
