### ISSUE TITLE
Clock moves onto lifelines

### ISSUE THREAD

**Issue by daniel-moon32** [BeautifulTrouble/h4i-uiuc-climate-clock-widget#92]
**Describe the bug**

**To Reproduce**

1. Go mobile view
2. Go to fullscreen
3. See screen

**Expected behavior**

**Screenshots**
![Screenshot_20220430-103845_Firefox.jpg](https://user-images.githubusercontent.com/36148173/166112384-a34a9835-b9d9-41ec-adb7-344ecc7b3a71.jpg)

**Comment by Archna-1** [comment]
Closed with #106
